[package]
name = "mykv"
version = "0.1.0"
authors = ["leoppro"]

[dependencies]
byteorder = "1.2.4"
bincode = "1.0.1"
chashmap = "2.2.0"
bytes = "0.4.9"
serde_derive = "1.0.71"
serde = "1.0.71"
log = "0.4.3"
env_logger = "0.5.12"